### ISSUE TITLE
Miscs mistakes

### ISSUE THREAD

**Issue by Carreau** [TwistedHardware/mltutorial#1]
Thanks for the video, great in general. A few mistakes though, I know we are bad at communications.
- kernels are installed with `ipython kernel-spec install-self`, not manually, you would miss some resources (logo among others)
- Avoir Julia+Python+R,  it convey that we only support these languages.
- the kernel.png is a nice approximation but will be confusing in the case of the notebook where you have an intermediate layer like the notebook server, and also you have broadcast sockets. It would be nice to have the text that this is just an "approximation" on how IPython works. It might lead to confusion for future users. 
- It's bad practice to  give example that run on public IPs without https. 
- Colaboratory is no longer developped, please don't mention it, we are working on bringing the functionality of it through [jupyter drive](https://github.com/jupyter/jupyter-drive)
- unicode characters works with julia too.

**Comment by TwistedHardware** [comment]
Thank you Carreau .. Indeed programmers are not the best at conveying ideas to humans. We generally find computer more understanding.
1. I'll change the part about kernel installation.
2. I'll remove Julia+Python+R ..
3. I'll add some text clarifying that it is just an approximation.
4. I'm really not sure where did I use a public IP. The jupyter server was running on my local machine. If you are talking about the flask web-service, I was showing the capability of running a web service locally from within jupyter using the new terminal sessions.
5. I'll edit the part about Colaboratory and just talk about jupyter drive.
6. Thanks for the the tip about Julia. I'll add that.

**Comment by Carreau** [comment]
> You can serve static files using http://url:port/files/%FILE_PATH% like http://0.0.0.0:8888/files/myproject/README.html

Even on localhost, not setting up https allow other users/program running as nobody to access data they should not. Edge case maybe, but case nontheless.

> I'll remove Julia+Python+R

Yo can leave it, but it's more by chance than by design. We appreciate it, and Fernando make reference to it himself. Also if the community likes it, then so be it. 

Globally these are just comment/thoughts, you did a terrific job in making the video, 
and we would love to find more time to do that ourselves; or find people ready to do 
more documentation of what the notebook is. 

Thanks !

**Comment by TwistedHardware** [comment]
Could you please review the revised notebook.
http://nbviewer.ipython.org/github/twistedhardware/mltutorial/blob/master/notebooks/jupyter/1.Introduction.ipynb
